// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64QhXYt3Y0UWSE0c7Ciq9amtkt0rbdBQ',
    appId: '1:428182794556:web:c9b861b7335875e884ee39',
    messagingSenderId: '428182794556',
    projectId: 'zindgi-c6969',
    authDomain: 'zindgi-c6969.firebaseapp.com',
    storageBucket: 'zindgi-c6969.appspot.com',
    measurementId: 'G-GQ7MQ04YC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6uydtr5urHaRRSE91xSjOtXBJSdHJbE',
    appId: '1:428182794556:android:c489dea6ba3a9c8c84ee39',
    messagingSenderId: '428182794556',
    projectId: 'zindgi-c6969',
    storageBucket: 'zindgi-c6969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzZ2vu1BfRucEZg2wlZO2oWsYNfR5kgY',
    appId: '1:428182794556:ios:37a3c4d0b78853f084ee39',
    messagingSenderId: '428182794556',
    projectId: 'zindgi-c6969',
    storageBucket: 'zindgi-c6969.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
